ERROR - 2022-12-28 17:40:40 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\data-search\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\data-search\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'dataserach', 3308, '', 0)
#1 C:\xampp\htdocs\data-search\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\data-search\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\data-search\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\data-search\app\Controllers\dataController.php(55): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\data-search\system\CodeIgniter.php(927): App\Controllers\dataController->loginck()
#6 C:\xampp\htdocs\data-search\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\dataController))
#7 C:\xampp\htdocs\data-search\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\data-search\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\data-search\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\data-search\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\data-search\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\data-search\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\data-search\app\Controllers\dataController.php(55): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\data-search\system\CodeIgniter.php(927): App\Controllers\dataController->loginck()
#5 C:\xampp\htdocs\data-search\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\dataController))
#6 C:\xampp\htdocs\data-search\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\data-search\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-12-28 17:40:40 --> Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `admintbl`
WHERE `username` = :username:
AND `password` = :password:', [...], false)
 3 APPPATH\Controllers\dataController.php(55): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\dataController->loginck()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\dataController))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
